title: "Art for the Garden Party"
author: "[Your Name]"
email: "your-email@example.com"
description: "A portfolio for a nude portrait artist"
baseurl: "" # Leave empty for GitHub Pages
url: "https://gardenpartyart.github.io" # Your GitHub Pages URL
